### ISSUE TITLE
Remove/disable notification that appears when new window is opened

### ISSUE THREAD

**Issue by bkromhout** [onatm/open-in-new-window#1]
Hi, a quick request for you: can you remove the notification that is shown when the context menu item is used to open a folder in a new window? (The one which says `Opening ${uri.path} in new window!`, that is).

It seems unnecessary since it is obvious that the new window has opened. Also, it's a bit bothersome, because it means I have to go back to the other window to dismiss it. I think it would be cleaner without it :)

**Comment by onatm** [comment]
Hey @bkromhout, sounds reasonable to me. Could you send a PR for it?
